# Generated by Django 4.2.11 on 2026-04-20 17:26

from django.db import migrations, models


def ensure_searchquery_table(apps, schema_editor):
    SearchQuery = apps.get_model('weather', 'SearchQuery')
    existing_tables = schema_editor.connection.introspection.table_names()

    if SearchQuery._meta.db_table not in existing_tables:
        schema_editor.create_model(SearchQuery)


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            ensure_searchquery_table,
            migrations.RunPython.noop,
        ),
        migrations.RenameField(
            model_name='searchquery',
            old_name='query',
            new_name='location',
        ),
        migrations.AddField(
            model_name='searchquery',
            name='weather_data',
            field=models.JSONField(default=dict),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(
                fields=['location', '-timestamp'],
                name='weather_sea_locatio_5bb5f1_idx',
            ),
        ),
    ]
